services:
  redis:
    build:
      context: infrastructure/redis
      dockerfile: Dockerfile
      target: base
    networks:
      - internal
    restart: unless-stopped
    container_name: redis_server
    hostname: redis_server
    ports:
      - 127.0.0.1:6379:6379
  db_server:
    image: "postgres:15.3-alpine"
    networks:
      - internal
    ports:
      - 127.0.0.1:5432:5432
    restart: unless-stopped
    volumes:
      - ./infrastructure/datadir/pgdata:/var/lib/postgresql/pgdata
      - ./infrastructure/postgre/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB_NAME}
      POSTGRES_USER: ${POSTGRESQL_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_DB_PASSWORD}
      PGDATA: /var/lib/postgresql/pgdata
  kafka-0:
    image: "docker.io/bitnami/kafka:3.5.1-debian-11-r7"
    networks:
      - internal
    ports:
      - 127.0.0.1:9092:9092
      - 127.0.0.1:9093:9093
    restart: unless-stopped
    environment:
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./infrastructure/datadir/kafka_0_dev_data:/bitnami/kafka
  jaeger:
    image: "jaegertracing/all-in-one"
    networks:
      - internal
    container_name: trace_logger
    hostname: trace_logger
    environment:
      SPAN_STORAGE_TYPE: badger
      BADGER_EPHEMERAL: false
      BADGER_DIRECTORY_VALUE: /badger/data
      BADGER_DIRECTORY_KEY: /badger/key
      COLLECTOR_OTLP_ENABLED: true
    #      COLLECTOR_ZIPKIN_HOST_PORT: 9411
    #      COLLECTOR_ZIPKIN_HTTP_ENABLED: true
    ports:
      - 16686:16686
      - 14268:14268
      #- 9411:9411
      - 5778:5778
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
    restart: unless-stopped
    volumes:
      - ./infrastructure/datadir/jaeger:/badger

networks:
  internal:
    name: internal