services:
  npm_cache:
    build:
      context: ./
      dockerfile: npm_cache/Dockerfile
    image: npm_cache
  control_center:
    build:
      context: control_center
      dockerfile: Dockerfile
      target: dev
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    networks:
      - internal
    depends_on:
      - npm_cache
    restart: unless-stopped
  rss_fetch:
    build:
      context: workers/rss_fetch
      dockerfile: Dockerfile
      target: dev
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    networks:
      - internal
    depends_on:
      - npm_cache
    restart: unless-stopped
  analysis:
    build:
      context: workers/analysis
      dockerfile: Dockerfile
      target: dev
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    networks:
      - internal
    depends_on:
      - npm_cache
    restart: unless-stopped
  link_writer:
    build:
      context: workers/link_writer
      dockerfile: Dockerfile
      target: dev
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    networks:
      - internal
    depends_on:
      - npm_cache
    restart: unless-stopped
  err_log_writer:
    build:
      context: workers/err_log_writer
      dockerfile: Dockerfile
      target: dev
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    networks:
      - internal
    depends_on:
      - npm_cache
    restart: unless-stopped
  link_fix_detector:
    build:
      context: workers/link_fix_detector
      dockerfile: Dockerfile
      target: dev
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    networks:
      - internal
    depends_on:
      - npm_cache
    restart: unless-stopped

networks:
  internal:
    name: internal