services:
  kafka_ui:
    image: "provectuslabs/kafka-ui:latest"
    networks:
      - internal
    ports:
      - 127.0.0.1:8081:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    restart: unless-stopped
    volumes:
      - ./infrastructure/kafka-ui/config-dev.yml:/etc/kafkaui/dynamic_config.yaml
networks:
  internal:
    name: internal